const HOME_PRODUCTS = [
  {
    id: 'sh-001',
    name: 'Inkweto Pro',
    category: 'shoes',
    price: 18000,
    oldPrice: 25000,
    badge: 'Sale',
    meta: 'Best seller',
    image: 'img/top 1 imyeto.jpeg',
    description: 'Comfort shoes for daily wear.',
    link: 'product-details1.html'
  },
  {
    id: 'wa-002',
    name: 'Isaha Smart',
    category: 'watches',
    price: 28000,
    oldPrice: 32000,
    badge: 'Hot',
    meta: 'Smart pick',
    image: 'img/top2 isaha.jpeg',
    description: 'Slim smartwatch with notifications.',
    link: 'product-details2.html'
  },
  {
    id: 'ba-003',
    name: 'Leather Bag',
    category: 'bags',
    price: 15000,
    oldPrice: 20000,
    badge: 'Deal',
    meta: 'Office ready',
    image: 'img/top 3igikapu.jpeg',
    description: 'Elegant bag with clean finish.',
    link: 'product-details1.html'
  },
  {
    id: 'el-004',
    name: 'Android TV',
    category: 'electronics',
    price: 20000,
    oldPrice: 26000,
    badge: 'New',
    meta: 'Living room',
    image: 'img/top 4 android tv.jpeg',
    description: 'Compact smart TV for home entertainment.',
    link: 'product-details1.html'
  },
  {
    id: 'fa-005',
    name: 'Classic T-Shirt',
    category: 'fashion',
    price: 10000,
    oldPrice: 15000,
    badge: 'Sale',
    meta: 'Soft cotton',
    image: 'img/Reduced  T-SHIRT CLASSIC.jpeg',
    description: 'Everyday premium cotton tee.',
    link: 'product-details1.html'
  },
  {
    id: 'ba-006',
    name: 'Bag Trendy',
    category: 'bags',
    price: 15000,
    oldPrice: 20000,
    badge: 'Promo',
    meta: 'Travel easy',
    image: 'img/Reduced  Bag trendy.jpeg',
    description: 'Light backpack with multiple pockets.',
    link: 'product-details1.html'
  },
  {
    id: 'sh-007',
    name: 'Sneaker Lite',
    category: 'shoes',
    price: 21000,
    oldPrice: 30000,
    badge: 'Sale',
    meta: 'Running',
    image: 'img/Reduced sneaker  lite.jpeg',
    description: 'Breathable shoe for active days.',
    link: 'product-details1.html'
  },
  {
    id: 'ph-008',
    name: 'Phone Smart',
    category: 'phones',
    price: 200000,
    oldPrice: 250000,
    badge: 'Top',
    meta: '128GB',
    image: 'img/Reduced  phone  Smart.jpeg',
    description: 'Smooth performance and sharp camera.',
    link: 'product-details1.html'
  },
  {
    id: 'sh-009',
    name: 'Trail Sneakers',
    category: 'shoes',
    price: 20000,
    oldPrice: 25000,
    badge: 'Pick',
    meta: 'Outdoor',
    image: 'img/Reduced  trail sneakers.jpeg',
    description: 'Strong grip and everyday comfort.',
    link: 'product-details1.html'
  },
  {
    id: 'fa-010',
    name: 'Butterfly Set',
    category: 'fashion',
    price: 10000,
    oldPrice: 15000,
    badge: 'Deal',
    meta: 'Accessories',
    image: 'img/Reduced  butterfly elegan set.jpeg',
    description: 'Elegant fashion set for special looks.',
    link: 'product-details1.html'
  },
  {
    id: 'fa-011',
    name: 'Queen Set',
    category: 'fashion',
    price: 10000,
    oldPrice: 15000,
    badge: 'Trending',
    meta: 'Styled',
    image: 'img/Reduced  butterfly Queen Set.jpeg',
    description: 'Compact styled set loved by shoppers.',
    link: 'product-details1.html'
  },
  {
    id: 'sh-012',
    name: 'Cloud Sneakers',
    category: 'shoes',
    price: 18000,
    oldPrice: 25000,
    badge: 'New',
    meta: 'Soft step',
    image: 'img/Reduced  denim cloud sneakers.jpeg',
    description: 'Cloud cushioning for all-day wear.',
    link: 'product-details1.html'
  },
  {
    id: 'ph-013',
    name: 'Phone Smart 2',
    category: 'phones',
    price: 180000,
    oldPrice: 220000,
    badge: 'Value',
    meta: 'Fast chip',
    image: 'img/Reduced  phone  Smart2.jpeg',
    description: 'Fast phone with reliable battery.',
    link: 'product-details1.html'
  },
  {
    id: 'fa-014',
    name: 'Fashion Jacket',
    category: 'fashion',
    price: 18000,
    oldPrice: 24000,
    badge: 'New',
    meta: 'Layer up',
    image: 'img/All Products  1990 ajf kkF.jpeg',
    description: 'Sharp jacket for casual days.',
    link: 'product-details1.html'
  },
  {
    id: 'el-015',
    name: 'Earbuds Air',
    category: 'electronics',
    price: 21000,
    oldPrice: 26000,
    badge: 'Hot',
    meta: 'Wireless',
    image: 'img/All Products  SPOERTS.jpeg',
    description: 'Small wireless earbuds with clear sound.',
    link: 'product-details1.html'
  },

    {
    id: 'el-016',
    name: 'Earbuds Air',
    category: 'electronics',
    price: 21000,
    oldPrice: 26000,
    badge: 'Hot',
    meta: 'Wireless',
    image: '.jpeg',
    description: 'Small wireless earbuds with clear sound.',
    link: 'product-details1.html'
  }
];